### ISSUE TITLE
TASK [mariadb : Get list of hosts for the root user.] fails when ansible runs in --check mode

### ISSUE THREAD

**Issue by xoxys** [owncloud-ansible/mariadb#1]
I would like to be able to verify that my installation will succeed prior to actually changing configurations and installing software.

Ansible doesn’t provide roll-back mechanisms. To test a playbook I would like to be able to utilize e.g. `ansible-playbook -i inventories/rheL7-full/hosts playbooks/setup.yml --check`. Apparently this fails when the database server isn’t ready yet.

```
TASK [mysql : Get list of hosts for the root user.] ***********************************************************************************************************************************************
fatal: [db1]: FAILED! => {“changed”: false, “cmd”: [“mysql”, “-NBe”, “SELECT Host FROM mysql.user WHERE User = ‘root’ ORDER BY (Host=‘localhost’) ASC”], “delta”: “0:00:00.005282”, 
“end”: “2019-11-07 19:08:40.719975”, “msg”: “non-zero return code”, “rc”: 1, “start”: “2019-11-07 19:08:40.714693”, “stderr”: “ERROR 2002 (HY000): Can’t connect to local MySQL server through socket ‘/var/lib/mysql/mysql.sock’ (2)”, 
“stderr_lines”: [“ERROR 2002 (HY000): Can’t connect to local MySQL server through socket ‘/var/lib/mysql/mysql.sock’ (2)”], “stdout”: “”, “stdout_lines”: []}

```

**Comment by xoxys** [comment]
Some technical background information as notes:

- check mode is implemented individual by each module
- check mode should not modify anything on the target host

Current issue:

- enable and start a systemd daemon is technically a change on the target
- therefor running the playbook in check mode will not start e.g. MariaDB service and some dependency tasks will fail

Needs some investigation

**Comment by enbrnz** [comment]
A check mode can't work in this role.
